//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BD_26.Models
{
    using System;
    using System.Collections.Generic;
    using System.Web;

    public partial class Patient_Requests
    {
        public string Patient_Ssn { get; set; }
        public string Patient_name { get; set; }
        public string bloodtype { get; set; }
        public int permission_ID { get; set; }
        public string permission_path { get; set; }
        public string Status { get; set; }
        public HttpPostedFileBase Imagefile { get; set; }
    }
}
